<div class="grid grid-pad hideOnTablet">
		<div class="col-7-12">
			<div class="content" style="text-align: center;"><img src="images/header-installandwin.png" alt="Install and Win!" /></div>
		</div>
		<div class="col-5-12 mobile-col-1-1 mobileCenter">
			<div class="content"><img src="images/header-entertowin.png" alt="Enter to Win!" /></div>
		</div>
	</div>
	<div class="grid showOnTablet" style="margin: 0 0; padding: 0 0;">
		<div class="mobile-col-1-1 mobileCenter" style="margin: 0 0; padding: 0 0;">
			<img src="images/header2.jpg" alt="Enter to Win!" />
		</div>
	</div>
	<div class="grid showOnMobile" style="margin: 0 0; padding: 0 0;">
		<div class="mobile-col-1-1 mobileCenter" style="margin: 0 0; padding: 0 0;">
			<img src="images/header3.jpg" alt="Enter to Win!" />
		</div>
	</div>
